site_name: "SFG Analytics Platform"
site_description: "Documentation hub for Salt Free Gaming's business intelligence platform"
site_url: "https://saltfreegaming.github.io/analytics-docs"
repo_url: "https://github.com/saltfreegaming/analytics-docs"
site_dir: static
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - content.code.copy
nav:
  - Home: index.md
  - Credits: credits.md
  - Project Management:
      - Dashboard Workflows: project-management/dashboard-workflows.md
      - Overview: project-management/stakeholder-overview.md
      - Decision Briefs:
          - Inaccurate Account Calibration: project-management/decision-briefs/inaccurate-account-calibration.md
  - Platform:
      - Apache Superset:
          - Software Details: platform/superset.md
          - Style Guidelines: platform/superset-style-guidelines.md
  - Dashboards:
      - Dashboard docs go here...: dashboards/final-dashboard-docs-here.md
  - Supporting Docs:
      - Main DB Schema Anatomy: project-management/database/main-schema.md
extra:
  analytics_phase: "minimum"
